spring.application.name=api-alunos
spring.datasource.url=jdbc:postgresql://localhost:5432/estudosdb
spring.datasource.username=estudo
spring.datasource.password=estudo123
spring.jpa.hibernate.ddl-auto=update

spring.mongodb.uri=mongodb://root:root123@localhost:27017/admin
